apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hh-resume-auto-boost.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hh-resume-auto-boost.labels" . | nindent 4 }}
data:
  config.json: {{ .Values.config | toJson | quote }}
