{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hh-resume-auto-boost.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hh-resume-auto-boost.labels" . | nindent 4 }}
type: Opaque
stringData:
  LOGIN: {{ .Values.credentials.login | quote }}
  PASSWORD: {{ .Values.credentials.password | quote }}
{{- end }}
